# Generated by Django 5.1.2 on 2024-10-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vp_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dormitory",
            field=models.CharField(
                blank=True,
                choices=[("punk", "ПУНК"), ("vunk", "ВУНК"), ("unk", "Не указано")],
                default="unk",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="faculty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("matmeh", "Математико-Механический"),
                    ("pmpu", "Прикладной математики, процессов управдения"),
                    ("chemfac", "Химический"),
                    ("physfac", "Физический"),
                    ("unk", "Не указан"),
                ],
                default="unk",
                max_length=50,
            ),
        ),
    ]
