# Generated by Django 5.1.2 on 2024-11-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vp_users", "0002_alter_user_dormitory_alter_user_faculty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="patronymic",
        ),
        migrations.RemoveField(
            model_name="user",
            name="surname",
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, upload_to="profile_photos"),
        ),
    ]
