# Generated by Django 5.1.2 on 2024-11-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vp_users", "0003_remove_user_patronymic_remove_user_surname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images_manager/image_folder/user/"),
        ),
    ]
