# Generated by Django 5.1.2 on 2024-11-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vp_users", "0004_alter_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                default="images_manager/image_folder/default/user_default.jpg",
                upload_to="images_manager/image_folder/user/",
            ),
        ),
    ]
