# Generated by Django 5.1.2 on 2024-11-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vp_users", "0005_alter_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="faculty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("matmeh", "Математико-Механический"),
                    ("pmpu", "Прикладной математики, процессов управления"),
                    ("chemfac", "Химический"),
                    ("physfac", "Физический"),
                    ("unk", "Не указан"),
                ],
                default="unk",
                max_length=50,
            ),
        ),
    ]
