# Generated by Django 5.1.4 on 2024-12-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vp_users", "0006_alter_user_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="activation_code_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
