# Generated by Django 5.1.4 on 2024-12-17 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vp_forum", "0008_remove_salecard_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleCardImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("photo", models.ImageField(upload_to="post_images/")),
                (
                    "salecard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="vp_forum.salecard"
                    ),
                ),
            ],
        ),
    ]
