# Generated by Django 5.1.2 on 2024-11-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vp_forum", "0002_salecard_description_alter_salecard_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="salecard",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images_manager/image_folder/salecard/"),
        ),
    ]
