# Generated by Django 5.1.2 on 2024-11-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vp_forum", "0003_salecard_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salecard",
            name="photo",
            field=models.ImageField(
                default="images_manager/image_folder/default/salecard_default.jpg",
                upload_to="images_manager/image_folder/salecard/",
            ),
        ),
    ]
