# Generated by Django 5.1.4 on 2024-12-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vp_forum", "0008_remove_salecard_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="salecard",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="salecards", to="vp_forum.category"),
        ),
    ]
