name: Check code and run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
         python-version: '3.12'
      - name: install poetry
        run: |
         python -m pip install --upgrade pip
         pip install poetry

      - name: install dependencies
        run: poetry install

      - name: isort
        run: poetry run isort . --check --diff

      - name: black
        run: poetry run black . --check --diff --color

      - name: ruff
        run: poetry run ruff check . --diff

      - name: mypy
        run: poetry run mypy .

      # Here should be django tests. WIP.
